(function () {
  "use strict";
  const app = document.querySelector("#admin-app");
  const YEARS = Array.from({ length: window.TeresaStore.YEAR_MAX - window.TeresaStore.YEAR_MIN + 1 }, (_, index) => window.TeresaStore.YEAR_MIN + index);
  const params = new URLSearchParams(window.location.search);
  let currentYear = Number(params.get("year")) || 2026;
  let editingId = params.get("activity") || "";
  let selectedImages = [];
  let pendingCover = "";
  const TOPICS = ["Phụng vụ", "Thánh lễ", "Lễ Quan thầy", "Đại lễ", "Thành lập", "Phục Sinh", "Giáng Sinh", "Thiện nguyện", "Tĩnh tâm", "Gắn kết", "Hội thao", "Hòa nhạc", "Cộng đoàn", "Khác"];
  const escapeHTML = (value = "") => String(value).replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character]);
  const message = (text, type = "success") => `<p class="admin-message ${type}" role="status">${escapeHTML(text)}</p>`;
  const topicSelect = (name, value = "") => `<select name="${name}" required>${TOPICS.map((topic) => `<option value="${topic}" ${topic === value ? "selected" : ""}>${topic}</option>`).join("")}</select>`;
  const normalizeTeamMember = (member) => typeof member === "string" ? { name: member, photo: "" } : (member || {});
  const teamMemberRow = (member = {}) => {
    const data = normalizeTeamMember(member);
    return `<div class="team-member-editor"><input class="team-member-name" value="${escapeHTML(data.name || "")}" placeholder="Tên thành viên" /><input class="team-member-photo" value="${escapeHTML(data.photo || "")}" placeholder="Đường dẫn ảnh (tùy chọn)" /><label class="mini-upload">Tải ảnh<input class="team-member-upload" type="file" accept="image/*" /></label><img class="member-photo-preview" src="${escapeHTML(data.photo || "images/hero.jpg")}" data-media-src="${escapeHTML(data.photo || "")}" alt="" ${data.photo ? "" : "hidden"} /><button class="danger-link" type="button" data-remove-team-member aria-label="Xóa thành viên">×</button></div>`;
  };
  const teamRow = (team = {}) => `<article class="team-row"><label>Tên ban<input class="team-name" value="${escapeHTML(team.name || "")}" placeholder="Ví dụ: Ban Truyền thông" required /></label><div class="team-members-editor"><div class="team-members-list">${(team.members || []).map(teamMemberRow).join("")}</div><button class="text-button" type="button" data-add-team-member>+ Thêm thành viên</button></div><button class="danger-link" type="button" data-remove-team>Xóa ban</button></article>`;

  function loginView(note = "") {
    const isCloud = window.TeresaStore.isFirebaseConfigured() && window.TeresaStore.isSourceApiConfigured();
    const cloudStatusNote = isCloud
      ? `<p class="cloud-status active">🔥 Hệ thống Đám mây Firebase đã sẵn sàng.</p>`
      : `<p class="cloud-status warning">⚠️ Đang chạy chế độ Cục bộ. Vui lòng nhập thông số vào <code>js/firebase-config.js</code> để bật Đám mây.</p>`;

    app.innerHTML = `<section class="admin-login"><div class="admin-login-card"><p class="eyebrow">Khu quản trị</p><h1>Chào người giữ ký ức.</h1><p>Đăng nhập để cập nhật nhật ký, hoạt động và ảnh cho toàn bộ ca đoàn.</p>${cloudStatusNote}${note}<form id="login-form"><label>${isCloud ? "Email Admin" : "Tài khoản"}<input name="username" ${isCloud ? 'type="email" placeholder="admin@domain.com"' : ''} autocomplete="username" required /></label><label>Mật khẩu<span class="password-control"><input name="password" type="password" autocomplete="current-password" required /><button type="button" data-password-toggle aria-label="Hiện mật khẩu">Hiện</button></span></label><button class="button button-primary" type="submit">Đăng nhập →</button></form><small>${isCloud ? "Đăng nhập bằng Email & Mật khẩu Admin đã tạo trên Firebase Auth Console." : "Tài khoản khởi tạo: <strong>admin</strong> · mật khẩu: <strong>teresa2026</strong>."}</small></div></section>`;
    document.querySelector("[data-password-toggle]").addEventListener("click", (event) => { const input = document.querySelector('[name="password"]'); const visible = input.type === "text"; input.type = visible ? "password" : "text"; event.currentTarget.textContent = visible ? "Hiện" : "Ẩn"; event.currentTarget.setAttribute("aria-label", visible ? "Hiện mật khẩu" : "Ẩn mật khẩu"); });
    document.querySelector("#login-form").addEventListener("submit", async (event) => {
      event.preventDefault();
      const form = new FormData(event.currentTarget);
      const res = await window.TeresaStore.login(form.get("username"), form.get("password"));
      if (res.success) dashboard();
      else loginView(message(res.message || "Tài khoản hoặc mật khẩu chưa đúng.", "error"));
    });
  }

  async function activityRows(data) {
    return data.activities.map((activity) => `<article class="admin-activity-row ${activity.id === editingId ? "selected" : ""}"><div><small>${escapeHTML(activity.type)} · ${escapeHTML(activity.date)}</small><h3>${escapeHTML(activity.title)}</h3><p>${escapeHTML(activity.description)}</p></div><div class="admin-row-actions"><a href="activity.html?year=${data.year}&id=${encodeURIComponent(activity.id)}" target="_blank" rel="noopener">Xem ↗</a><button type="button" data-edit-activity="${escapeHTML(activity.id)}">Sửa</button><button class="danger-link" type="button" data-delete-activity="${escapeHTML(activity.id)}">Xóa</button></div></article>`).join("");
  }

  function activityForm(activity = {}) {
    const images = [...(activity.images || []), ...selectedImages];
    const topic = activity.topic || activity.type || "Khác";
    const coverImage = pendingCover || activity.coverImage || images[0]?.src || "images/hero.jpg";
    return `<form class="admin-form" id="activity-form"><input type="hidden" name="id" value="${escapeHTML(activity.id || "")}" /><input type="hidden" name="coverImage" value="${escapeHTML(coverImage)}" /><div class="admin-form-title"><div><p class="eyebrow">Hoạt động</p><h2>${activity.id ? "Chỉnh sửa hoạt động" : "Thêm hoạt động"}</h2></div><button class="text-button" type="button" id="clear-activity">Tạo mục mới</button></div><div class="activity-context"><span>Năm cố định: <strong>${currentYear}</strong></span><span>Chủ đề được giữ khi chỉ nhập/sửa bài viết.</span></div><div class="form-grid two"><label>Tên hoạt động<input name="title" required value="${escapeHTML(activity.title || "")}" /></label><label>Ngày / thời gian<input name="date" required value="${escapeHTML(activity.date || "")}" placeholder="Ví dụ: 01.10.2026" /></label><label>Loại hoạt động<input name="type" required value="${escapeHTML(activity.type || "Thánh lễ")}" /></label><label>Chủ đề ảnh${topicSelect("topic", topic)}</label></div><label>Tóm tắt<input name="description" required value="${escapeHTML(activity.description || "")}" /></label><label>Bài viết chi tiết<textarea name="body" rows="7" required>${escapeHTML(activity.body || activity.description || "")}</textarea></label><div class="word-import"><strong>Nhập bài viết Word</strong><input id="word-import" type="file" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" /><small id="word-import-note">Chỉ nhập nội dung vào bài viết; năm và chủ đề phía trên không bị thay đổi.</small></div><div class="cover-picker"><div class="cover-picker-copy"><strong>Ảnh trang mở đầu hoạt động</strong><small>Ảnh này hiển thị ở đầu trang bài viết riêng. Với hoạt động đã có: chọn ảnh rồi bấm “Lưu ảnh bìa ngay”.</small><code>${escapeHTML(coverImage)}</code></div><img class="cover-preview" data-media-src="${escapeHTML(coverImage)}" src="images/hero.jpg" alt="Xem trước ảnh trang mở đầu" /><label class="cover-upload">Thay ảnh<input id="activity-cover" type="file" accept="image/*" /></label><button class="button" id="save-cover" type="button" hidden>Lưu ảnh bìa ngay</button><small class="cover-status" id="cover-status">${activity.id ? "Chọn ảnh mới, rồi bấm “Lưu ảnh bìa ngay”." : "Chọn ảnh, sau đó bấm “Lưu hoạt động” để tạo hoạt động kèm ảnh bìa."}</small></div><div class="media-picker"><div><strong>Ảnh của hoạt động</strong><p>Hãy chọn chủ đề trước, sau đó ảnh tải lên sẽ được lưu vào kho ảnh năm ${currentYear} và đính kèm mục này.</p></div><input id="activity-images" type="file" accept="image/*" multiple /><div id="selected-images" class="selected-media">${images.map((image) => `<span data-source="${escapeHTML(image.src)}">${escapeHTML(image.caption || "Ảnh đã đính kèm")} <button type="button" data-remove-image="${escapeHTML(image.src)}" aria-label="Gỡ ảnh">×</button></span>`).join("")}</div></div><button class="button button-primary" type="submit">Lưu hoạt động</button></form>`;
  }

  function overviewForm(data) {
    const overview = data.overview;
    const yearMark = data.yearMark || {};
    return `<form class="admin-form compact-form" id="overview-form"><div class="admin-form-title"><div><p class="eyebrow">Nhật ký ${data.year}</p><h2>Thông tin năm</h2></div><a href="year.html?year=${data.year}" target="_blank" rel="noopener">Xem trang năm ↗</a></div><label>Nhãn giới thiệu<input name="eyebrow" value="${escapeHTML(overview.eyebrow)}" /></label><label>Tiêu đề<input name="title" value="${escapeHTML(overview.title)}" /></label><label>Tóm tắt<textarea name="summary" rows="3">${escapeHTML(overview.summary)}</textarea></label><label>Bài giới thiệu<textarea name="longDescription" rows="6">${escapeHTML(overview.longDescription)}</textarea></label><label>Ảnh bìa (đường dẫn ảnh trong source)<input name="coverImage" value="${escapeHTML(overview.coverImage)}" /></label><div class="form-divider"><strong>Khung Dấu ấn</strong><small>Khung này có chiều cao cố định trên trang năm; nội dung dài sẽ không làm nó giãn ra.</small></div><label>Tiêu đề dấu ấn<input name="yearMarkTitle" value="${escapeHTML(yearMark.title)}" /></label><label>Dòng mô tả / ngày nổi bật<input name="yearMarkHighlight" value="${escapeHTML(yearMark.highlight)}" /></label><button class="button" type="submit">Lưu thông tin năm</button></form>`;
  }

  function leadershipForm(data) {
    const labels = { chaplain: "Cha đặc trách", leader: "Trưởng ca đoàn", deputyLeader: "Phó ca đoàn", conductor: "Ca trưởng", treasurer: "Thủ quỹ" };
    const leadership = data.leadership || {};
    const teams = leadership.teams || (leadership.serviceTeams || []).map((name) => ({ name, members: [] }));
    return `<form class="admin-form compact-form" id="leadership-form"><div class="admin-form-title"><div><p class="eyebrow">Nhân sự ${data.year}</p><h2>Ban điều hành</h2></div></div><p class="storage-note">Mỗi người có thể gắn ảnh bằng đường dẫn hoặc tải trực tiếp lên Cloudflare R2. Không chọn ảnh thì thẻ vẫn hiển thị tên như cũ.</p><div class="leadership-people-editor">${Object.entries(labels).map(([key, label]) => `<div class="leadership-person-editor"><label>${label}<input name="${key}" value="${escapeHTML(leadership[key]?.name || "")}" placeholder="Tên người phụ trách" /></label><input class="leadership-photo" data-role-key="${key}" value="${escapeHTML(leadership[key]?.photo || "")}" placeholder="Đường dẫn ảnh (tùy chọn)" /><label class="mini-upload">Tải ảnh<input class="leadership-photo-upload" data-role-key="${key}" type="file" accept="image/*" /></label><img class="member-photo-preview" src="${escapeHTML(leadership[key]?.photo || "images/hero.jpg")}" data-media-src="${escapeHTML(leadership[key]?.photo || "")}" alt="" ${leadership[key]?.photo ? "" : "hidden"} /></div>`).join("")}</div><div class="teams-editor"><div class="teams-heading"><strong>Các ban phục vụ & thành viên</strong><button type="button" class="text-button" id="add-team">+ Thêm ban</button></div><div id="teams-list">${teams.map(teamRow).join("") || '<p class="empty-note">Chưa có ban nào. Bấm “Thêm ban” để bắt đầu.</p>'}</div></div><button class="button" type="submit">Lưu ban điều hành</button></form>`;
  }

  function membersForm(data) {
    const members = data.members || {};
    return `<form class="admin-form compact-form" id="members-form"><div class="admin-form-title"><div><p class="eyebrow">Thống kê ${data.year}</p><h2>Thành viên</h2></div></div><div class="form-grid three"><label>Tổng số<input name="total" type="number" min="0" value="${Number(members.total || 0)}" /></label><label>In · thêm mới<input name="new" type="number" min="0" value="${Number(members.new || 0)}" /></label><label>Out · nghỉ<input name="inactive" type="number" min="0" value="${Number(members.inactive || 0)}" /></label></div><label>Ghi chú<textarea name="notes" rows="3">${escapeHTML(members.notes || "")}</textarea></label><button class="button" type="submit">Lưu số liệu thành viên</button></form>`;
  }

  async function mediaPanel() {
    const media = await window.TeresaStore.getMedia({ year: currentYear });
    const topics = [...new Set(["Tất cả", ...TOPICS, ...media.map((item) => item.topic)])];
    return `<section class="admin-panel media-panel"><div class="admin-form-title"><div><p class="eyebrow">Kho ảnh ${currentYear}</p><h2>Ảnh theo năm và chủ đề</h2></div></div><form id="media-form" class="media-upload-form"><input name="media" type="file" accept="image/*" required /><label>Chủ đề${topicSelect("topic", "Khác")}</label><input name="caption" placeholder="Chú thích ảnh" /><button class="button" type="submit">Thêm vào kho ảnh</button></form><p class="storage-note">Ảnh mới được lưu an toàn trên Cloudflare R2. Chọn một ảnh bên dưới để đặt làm ảnh mở đầu; tối đa 25 MB/ảnh.</p><div class="media-filters">${topics.map((topic, index) => `<button type="button" class="${index === 0 ? "active" : ""}" data-media-filter="${escapeHTML(topic)}">${escapeHTML(topic)}</button>`).join("")}</div><div class="media-library">${media.length ? media.map((item) => `<figure data-media-topic="${escapeHTML(item.topic)}"><img src="${item.src}" alt="${escapeHTML(item.alt)}" /><figcaption><strong>${escapeHTML(item.topic)}</strong><span>${escapeHTML(item.caption || item.filename)}</span><div class="media-card-actions"><button type="button" data-set-cover="${item.id}" ${editingId ? "" : "disabled"}>Đặt làm ảnh bìa</button><button type="button" data-delete-media="${item.id}" class="danger-link">Xóa ảnh</button></div></figcaption></figure>`).join("") : '<p class="empty-note">Chưa có ảnh tự tải lên cho năm này.</p>'}</div></section>`;
  }

  function adminError(error) {
    app.innerHTML = `<section class="admin-login"><div class="admin-login-card"><p class="eyebrow">Không thể mở khu quản trị</p><h1>Cần chạy qua máy chủ cục bộ.</h1><p>${escapeHTML(error.message || "Không thể đọc dữ liệu.")}</p><p>Trong VS Code, nhấp phải <code>index.html</code> và chọn <strong>Open with Live Server</strong>; không mở tệp trực tiếp bằng <code>file://</code>.</p><button class="button button-primary" type="button" id="retry-admin">Thử lại</button></div></section>`;
    document.querySelector("#retry-admin").addEventListener("click", () => dashboard());
  }

  async function dashboard(notice = "") {
    try { await renderDashboard(notice); } catch (error) { console.error(error); adminError(error); }
  }

  async function renderDashboard(notice = "") {
    const data = await window.TeresaStore.loadYear(currentYear);
    const selectedActivity = data.activities.find((activity) => activity.id === editingId);
    const isCloud = window.TeresaStore.isFirebaseConfigured() && window.TeresaStore.isSourceApiConfigured();
    const cloudBtn = "";

    app.innerHTML = `<section class="admin-shell"><div class="container"><div class="admin-heading"><div><p class="eyebrow">Quản trị kho lưu trữ ${isCloud ? "☁️ Firebase + Cloudflare R2" : "⚠️ Chưa kết nối Worker quản trị"}</p><h1>Nhật ký, hoạt động<br /><em>và những bức ảnh.</em></h1></div><div class="admin-tools">${cloudBtn}<button type="button" id="export-word">Xuất Word năm ${currentYear}</button><button type="button" id="export-archive">Sao lưu JSON</button><label class="import-label">Nhập sao lưu JSON<input id="import-archive" type="file" accept="application/json" /></label><button type="button" id="logout">Đăng xuất</button></div></div>${notice}<nav class="admin-years" aria-label="Chọn năm">${YEARS.map((year) => `<button type="button" class="${year === currentYear ? "active" : ""}" data-year="${year}">${year}</button>`).join("")}</nav><div class="admin-grid"><aside>${overviewForm(data)}${leadershipForm(data)}${membersForm(data)}</aside><div><section class="admin-panel"><div class="admin-form-title"><div><p class="eyebrow">Danh sách</p><h2>Hoạt động năm ${currentYear}</h2></div><button type="button" class="button" id="new-activity">+ Thêm hoạt động</button></div><div class="admin-activity-list">${await activityRows(data) || '<p class="empty-note">Chưa có hoạt động.</p>'}</div></section>${activityForm(selectedActivity)}${await mediaPanel()}</div></div></div></section>`;
    await window.TeresaStore.hydrateMedia(app);
    bindDashboard(data);
  }

  function download(filename, content) {
    const link = document.createElement("a");
    link.href = URL.createObjectURL(new Blob([content], { type: "application/json" }));
    link.download = filename; link.click(); URL.revokeObjectURL(link.href);
  }

  function bindDashboard(data) {
    document.querySelectorAll("[data-year]").forEach((button) => button.addEventListener("click", () => { currentYear = Number(button.dataset.year); editingId = ""; pendingCover = ""; dashboard(); }));
    document.querySelector("#logout").addEventListener("click", async () => { await window.TeresaStore.logout(); loginView(); });
    document.querySelector("#new-activity").addEventListener("click", () => { editingId = ""; pendingCover = ""; dashboard(); });
    document.querySelector("#clear-activity").addEventListener("click", () => { editingId = ""; pendingCover = ""; dashboard(); });
    document.querySelectorAll("[data-edit-activity]").forEach((button) => button.addEventListener("click", () => { editingId = button.dataset.editActivity; pendingCover = ""; dashboard(); }));
    document.querySelectorAll("[data-delete-activity]").forEach((button) => button.addEventListener("click", async () => { if (!confirm("Xóa hoạt động này? Ảnh trong kho không bị xóa.")) return; await window.TeresaStore.deleteActivity(currentYear, button.dataset.deleteActivity); editingId = ""; dashboard(message("Đã xóa hoạt động.")); }));
    document.querySelector("#overview-form").addEventListener("submit", async (event) => { event.preventDefault(); try { const values = Object.fromEntries(new FormData(event.currentTarget)); const { yearMarkTitle, yearMarkHighlight, ...overview } = values; data.overview = { ...data.overview, ...overview }; data.yearMark = { ...(data.yearMark || {}), title: yearMarkTitle || "Dấu ấn trong năm", highlight: yearMarkHighlight || "" }; await window.TeresaStore.saveYear(data); dashboard(message("Đã lưu thông tin năm và khung Dấu ấn.")); } catch (error) { dashboard(message(`Không thể lưu: ${error.message}`, "error")); } });
    document.querySelector("#add-team").addEventListener("click", () => { const list = document.querySelector("#teams-list"); if (list.querySelector(".empty-note")) list.innerHTML = ""; list.insertAdjacentHTML("beforeend", teamRow()); });
    document.querySelector("#teams-list").addEventListener("click", (event) => {
      const removeTeam = event.target.closest("[data-remove-team]");
      if (removeTeam) { removeTeam.closest(".team-row").remove(); if (!document.querySelector("#teams-list .team-row")) document.querySelector("#teams-list").innerHTML = '<p class="empty-note">Chưa có ban nào. Bấm “Thêm ban” để bắt đầu.</p>'; return; }
      const addMember = event.target.closest("[data-add-team-member]");
      if (addMember) { addMember.closest(".team-row").querySelector(".team-members-list").insertAdjacentHTML("beforeend", teamMemberRow()); return; }
      event.target.closest("[data-remove-team-member]")?.closest(".team-member-editor").remove();
    });
    document.querySelector("#leadership-form").addEventListener("change", async (event) => {
      const fileInput = event.target.closest(".leadership-photo-upload, .team-member-upload");
      if (!fileInput?.files?.[0]) return;
      const holder = fileInput.closest(".leadership-person-editor, .team-member-editor");
      const nameInput = holder.querySelector('[name], .team-member-name');
      const photoInput = holder.querySelector(".leadership-photo, .team-member-photo");
      const preview = holder.querySelector(".member-photo-preview");
      try {
        fileInput.disabled = true;
        const saved = await window.TeresaStore.saveMedia(fileInput.files[0], { year: currentYear, topic: "Cộng đoàn", caption: `Ảnh thành viên · ${nameInput.value.trim() || fileInput.files[0].name}`, alt: nameInput.value.trim() || fileInput.files[0].name });
        photoInput.value = saved.src;
        preview.src = saved.src; preview.dataset.mediaSrc = saved.src; preview.hidden = false;
      } catch (error) { dashboard(message(`Không thể tải ảnh thành viên: ${error.message}`, "error")); }
      finally { fileInput.disabled = false; }
    });
    document.querySelector("#leadership-form").addEventListener("submit", async (event) => { event.preventDefault(); try { const values = Object.fromEntries(new FormData(event.currentTarget)); const labels = ["chaplain", "leader", "deputyLeader", "conductor", "treasurer"]; const teams = [...event.currentTarget.querySelectorAll(".team-row")].map((row) => ({ name: row.querySelector(".team-name").value.trim(), members: [...row.querySelectorAll(".team-member-editor")].map((member) => ({ name: member.querySelector(".team-member-name").value.trim(), photo: member.querySelector(".team-member-photo").value.trim() })).filter((member) => member.name) })).filter((team) => team.name); const { deputyConductor, secretary, ...leadership } = data.leadership || {}; data.leadership = { ...leadership, ...Object.fromEntries(labels.map((key) => [key, { ...(leadership[key] || {}), name: values[key] || "Đang cập nhật", photo: event.currentTarget.querySelector(`.leadership-photo[data-role-key="${key}"]`).value.trim() }])), teams, serviceTeams: teams.map((team) => team.name) }; await window.TeresaStore.saveYear(data); dashboard(message("Đã lưu Ban điều hành, thành viên các ban và ảnh tương ứng.")); } catch (error) { dashboard(message(`Không thể lưu ban điều hành: ${error.message}`, "error")); } });
    document.querySelector("#members-form").addEventListener("submit", async (event) => { event.preventDefault(); try { const values = Object.fromEntries(new FormData(event.currentTarget)); data.members = { total: Number(values.total || 0), new: Number(values.new || 0), inactive: Number(values.inactive || 0), notes: values.notes || "" }; await window.TeresaStore.saveYear(data); dashboard(message("Đã lưu số liệu thành viên.")); } catch (error) { dashboard(message(`Không thể lưu số liệu thành viên: ${error.message}`, "error")); } });
    document.querySelectorAll("[data-password-toggle]").forEach((button) => button.addEventListener("click", () => { const input = button.parentElement.querySelector("input"); const visible = input.type === "text"; input.type = visible ? "password" : "text"; button.textContent = visible ? "Hiện" : "Ẩn"; button.setAttribute("aria-label", visible ? "Hiện mật khẩu" : "Ẩn mật khẩu"); }));
    document.querySelector("#activity-cover").addEventListener("change", async (event) => { const file = event.target.files[0]; if (!file) return; try { const form = event.target.closest("#activity-form"); const topic = form.querySelector('[name="topic"]').value || "Khác"; const saved = await window.TeresaStore.saveMedia(file, { year: currentYear, topic, caption: `Ảnh mở đầu · ${file.name}`, alt: file.name }); pendingCover = saved.src; form.querySelector('[name="coverImage"]').value = pendingCover; form.querySelector(".cover-picker code").textContent = pendingCover; form.querySelector(".cover-preview").src = saved.src; const saveCover = form.querySelector("#save-cover"); if (form.querySelector('[name="id"]').value) { saveCover.hidden = false; saveCover.disabled = false; form.querySelector(".cover-status").textContent = "Ảnh mới đã sẵn sàng. Bấm “Lưu ảnh bìa ngay” để áp dụng."; } else form.querySelector(".cover-status").textContent = "Ảnh mới đã sẵn sàng và sẽ được lưu cùng hoạt động khi bạn bấm “Lưu hoạt động”."; } catch (error) { dashboard(message(error.message, "error")); } });
    document.querySelector("#save-cover").addEventListener("click", async (event) => { const form = event.target.closest("#activity-form"); const activityId = form.querySelector('[name="id"]').value; const coverImage = form.querySelector('[name="coverImage"]').value; if (!activityId) { form.querySelector(".cover-status").textContent = "Hãy lưu hoạt động mới trước khi thay ảnh bìa riêng."; return; } try { const currentActivity = data.activities.find((item) => item.id === activityId); await window.TeresaStore.saveActivity(currentYear, { ...currentActivity, coverImage }); pendingCover = ""; dashboard(message("Đã thay ảnh trang mở đầu của hoạt động.")); } catch (error) { dashboard(message(`Không thể lưu ảnh bìa: ${error.message}`, "error")); } });
    document.querySelector("#activity-images").addEventListener("change", async (event) => { const files = [...event.target.files]; try { const saved = await Promise.all(files.map((file) => window.TeresaStore.saveMedia(file, { year: currentYear, topic: document.querySelector('[name="topic"]').value || "Khác", caption: file.name, alt: file.name }))); const images = saved.map((item) => ({ src: item.src, caption: item.caption, alt: item.alt })); selectedImages.push(...images); document.querySelector("#selected-images").insertAdjacentHTML("beforeend", images.map((image) => `<span data-source="${escapeHTML(image.src)}">${escapeHTML(image.caption)} <button type="button" data-remove-image="${escapeHTML(image.src)}" aria-label="Gỡ ảnh">×</button></span>`).join("")); } catch (error) { dashboard(message(error.message, "error")); } });
    document.querySelector("#selected-images").addEventListener("click", (event) => { const button = event.target.closest("[data-remove-image]"); if (!button) return; selectedImages = selectedImages.filter((image) => image.src !== button.dataset.removeImage); button.parentElement.remove(); });
    document.querySelector("#activity-form").addEventListener("submit", async (event) => { event.preventDefault(); try { const values = Object.fromEntries(new FormData(event.currentTarget)); const presentImages = [...event.currentTarget.querySelectorAll("[data-source]")].map((element) => ({ src: element.dataset.source, caption: element.textContent.replace("×", "").trim(), alt: element.textContent.replace("×", "").trim() })); const activity = { ...values, images: presentImages, coverImage: values.coverImage || pendingCover }; const saved = await window.TeresaStore.saveActivity(currentYear, activity); editingId = saved.id; selectedImages = []; pendingCover = ""; dashboard(message("Đã lưu hoạt động. Bạn có thể bấm “Xem” để mở bài viết công khai.")); } catch (error) { dashboard(message(`Không thể lưu hoạt động: ${error.message}`, "error")); } });
    document.querySelector("#media-form").addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { const saved = await window.TeresaStore.saveMedia(form.get("media"), { year: currentYear, topic: form.get("topic"), caption: form.get("caption"), alt: form.get("caption") || form.get("media").name }); data.gallery = [...(data.gallery || []), { src: saved.src, alt: saved.alt, caption: saved.caption, event: saved.topic }]; await window.TeresaStore.saveYear(data); dashboard(message("Đã thêm ảnh vào kho Cloudflare R2.")); } catch (error) { dashboard(message(error.message, "error")); } });
    document.querySelector("#word-import").addEventListener("change", async (event) => { const file = event.target.files[0]; if (!file) return; const note = document.querySelector("#word-import-note"); try { const text = await window.TeresaWord.readDocx(file); document.querySelector('[name="body"]').value = text; note.textContent = "Đã nhập nội dung Word. Hãy kiểm tra rồi bấm Lưu hoạt động."; } catch (error) { note.textContent = error.message; } });
    document.querySelectorAll("[data-media-filter]").forEach((button) => button.addEventListener("click", () => { document.querySelectorAll("[data-media-filter]").forEach((item) => item.classList.toggle("active", item === button)); document.querySelectorAll("[data-media-topic]").forEach((item) => { item.hidden = button.dataset.mediaFilter !== "Tất cả" && item.dataset.mediaTopic !== button.dataset.mediaFilter; }); }));
    document.querySelectorAll("[data-set-cover]").forEach((button) => button.addEventListener("click", async () => { const activity = data.activities.find((item) => item.id === editingId); if (!activity) { dashboard(message("Hãy bấm “Sửa” một hoạt động trước khi chọn ảnh bìa.", "error")); return; } try { await window.TeresaStore.saveActivity(currentYear, { ...activity, coverImage: button.dataset.setCover }); dashboard(message("Đã đặt ảnh trong kho làm ảnh trang mở đầu của hoạt động.")); } catch (error) { dashboard(message(`Không thể đặt ảnh bìa: ${error.message}`, "error")); } }));
    document.querySelectorAll("[data-delete-media]").forEach((button) => button.addEventListener("click", async () => { if (!confirm("Xóa ảnh này khỏi kho năm hiện tại? Ảnh sẽ không còn hiện trong album hoặc hoạt động.")) return; try { const source = button.dataset.deleteMedia; data.gallery = (data.gallery || []).filter((image) => image.src !== source); data.activities = data.activities.map((activity) => ({ ...activity, coverImage: activity.coverImage === source ? (activity.images?.find((image) => image.src !== source)?.src || "images/hero.jpg") : activity.coverImage, images: (activity.images || []).filter((image) => image.src !== source) })); await window.TeresaStore.saveYear(data); await window.TeresaStore.deleteMedia(source); dashboard(message("Đã xóa ảnh khỏi kho theo năm/chủ đề.")); } catch (error) { dashboard(message(`Không thể xóa ảnh: ${error.message}`, "error")); } }));
    document.querySelector("#export-word").addEventListener("click", () => window.TeresaWord.downloadWordYear(data));
    document.querySelector("#export-archive").addEventListener("click", async () => download(`teresa-archive-${new Date().toISOString().slice(0, 10)}.json`, JSON.stringify(await window.TeresaStore.exportArchive(), null, 2)));
    document.querySelector("#import-archive").addEventListener("change", async (event) => { const file = event.target.files[0]; if (!file || !confirm("Nhập dữ liệu sao lưu và ghi đè các năm/ảnh trùng lặp?")) return; try { await window.TeresaStore.importArchive(JSON.parse(await file.text())); dashboard(message("Đã nhập dữ liệu sao lưu.")); } catch (error) { dashboard(message(error.message, "error")); } });
  }

  document.addEventListener("DOMContentLoaded", async () => { await window.TeresaStore.waitForAuth(); window.TeresaStore.isAdmin() ? dashboard() : loginView(); });
})();
